grails:
    profile: plugin
    codegen:
        defaultPackage: grails.plugins.versionupdate
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
endpoints:
    enabled: false
    jmx:
        enabled: true
